# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'kde/pim/kpimtextedit' : '@same'
    'frameworks/ki18n': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kcompletion': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kcodecs': '@latest'
    'frameworks/kitemmodels': '@latest'
