# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kcolorscheme': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kcompletion': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kcodecs': '@latest-kf6'
    'frameworks/kitemmodels': '@latest-kf6'
    'libraries/ktextaddons': '@latest-kf6'

Options:
 # keyresolvercoretest sometimes takes very long on FreeBSD
 per-test-timeout: 120
 require-passing-tests-on: ['Linux', 'FreeBSD']
